.IX Title "EPOPTES 8"
.TH EPOPTES 8 "2011-09-22" epoptes epoptes

.SH "NAME"
epoptes \- A computer lab administration tool

.SH "SYNOPSIS"
.IX Header "SYNOPSIS"
epoptes

.SH "DESCRIPTION"
.IX Header "DESCRIPTION"
\fBepoptes\fP supports screen broadcasting, monitoring, sharing and locking, executing command on the clients, sending messages, and lots more.

.SH "AUTHOR"
.IX Header "AUTHOR"
Fotis Tsamis <ftsamis@gmail.com>, Alkis Georgopoulos <alkisg@gmail.com>.

.SH "LICENSE"
.IX Header "LICENSE"
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 or any later version published by the Free  Software  Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL-3.
