#!/bin/sh

die() {
    echo "$@" >&2
    exit 1
}

# Check if parameter is a command; `command -v` isn't allowed by POSIX
is_command() {
    local fun

    if [ -z "$is_command" ]; then
        command -v is_command >/dev/null ||
            die "Your shell doesn't support command -v"
        is_command=1
    fi
    for fun in "$@"; do
        command -v "$fun" >/dev/null || return $?
    done
}

re() {
    "$@" || die "Command failed: $*"
}

main() {
    is_command grdctl || die "Currently only gnome-remote-desktop is supported under wayland"
    re grdctl vnc set-auth-method password
    re grdctl vnc enable-view-only
    re grdctl vnc set-password "$1"
    re grdctl vnc enable
    if ! pgrep gnome-remote-de >/dev/null; then
        re systemctl --user start gnome-remote-desktop
    fi
    # TODO: trap to stop remote desktop, and wait?
}

main "$@"
