#!/bin/sh

###########################################################################
# Export some useful vars in the LTSP session environment.
# Sourced by LDM.
#
# Copyright (C) 2011 Alkis Georgopoulos <alkisg@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# On Debian GNU/Linux systems, the complete text of the GNU General
# Public License can be found in `/usr/share/common-licenses/GPL'.
###########################################################################

# Keep the following code synced with epoptes-client
def_iface=$(route -n | sed -n "/^0.0.0.0/s/.* //p")
def_iface=${def_iface:-$(route -n | awk '$2=="0.0.0.0" { print $8; exit }')}
if [ -n "$def_iface" ]; then
    MAC=$(ip -oneline -family inet link show dev "$def_iface" | sed "s/.*ether \([^ ]*\).*/\\1/")
    MAC=$(echo "$MAC" | sed 'y/abcdef-/ABCDEF:/;s/[^A-F0-9:]//g')
    test -n "$MAC" && CLIENT_ENV="$CLIENT_ENV LTSP_CLIENT_MAC=$MAC"
fi

# LTSP_FATCLIENT unfortunately isn't set in LTSP fat client sessions. Set it.
test -n "$LTSP_FATCLIENT" && CLIENT_ENV="$CLIENT_ENV LTSP_FATCLIENT=$LTSP_FATCLIENT"
